import pw from '@playwright/test';
const { chromium } = pw;
const b = await chromium.launch();
const page = await (await b.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
await page.goto('http://127.0.0.1:3001/');
await page.getByLabel('Email').fill('dev@kithlink.dev');
await page.getByLabel('Password').fill('DevOnly123!x');
await page.getByRole('button', { name: 'Sign in' }).click();
await page.waitForURL(/dashboard/);
await page.goto('http://127.0.0.1:3001/site');
await page.getByLabel('Hero title').fill('Happy Tails Every Day');
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.waitForTimeout(1500);
console.log('saved-visible:', await page.getByTestId('site-saved').isVisible().catch(()=>false));
await page.getByRole('button', { name: 'Publish', exact: true }).click();
await page.waitForTimeout(2500);
console.log('published-text:', await page.getByTestId('published-at').textContent().catch(e=>String(e)));
const r = await fetch('http://localhost:4000/public/v1/sites/happytail/index.html');
const h = await r.text();
console.log('html has new hero:', h.includes('Happy Tails Every Day'));
console.log('hero region:', (h.match(/<section class="hero">[\s\S]{0,220}/)||[''])[0]);
await b.close();
